#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# This cookbook
cookbook 'icinga',     :path => '.'

# Special cookbooks not from Opscode Community used here
cookbook 'pnp4nagios', :git => 'git@github.com:Bigpoint/pnp4nagios.git'
cookbook 'rrdcached',  :git => 'git@github.com:Bigpoint/rrdcached.git'
